package WebAssembly.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import WebAssembly.structure.Bytes;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SProperty;

public final class CustomSection__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0xf0ceec7784bd4104L, 0xb53284a17dffbb8aL, 0x601bfff8ed8786cbL, "WebAssembly.structure.CustomSection");

  public static final SMethod<Integer> byte_size_id60rZZzHEXgh = new SMethodBuilder<Integer>(new SJavaCompoundTypeImpl(Integer.TYPE)).name("byte_size").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(6925410296616702993L).languageId(0xb53284a17dffbb8aL, 0xf0ceec7784bd4104L).build2();
  public static final SMethod<byte[]> bytes_id60rZZzHEXiv = new SMethodBuilder<byte[]>(new SJavaCompoundTypeImpl(byte[].class)).name("bytes").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(6925410296616703135L).languageId(0xb53284a17dffbb8aL, 0xf0ceec7784bd4104L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(byte_size_id60rZZzHEXgh, bytes_id60rZZzHEXiv);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static int byte_size_id60rZZzHEXgh(@NotNull SNode __thisNode__) {
    byte[] nameLength = Bytes.u32BytesLeb128(SPropertyOperations.getString(__thisNode__, PROPS.name$49Oo).getBytes().length);
    byte[] lenBytes = Bytes.u32BytesLeb128(SPropertyOperations.getString(__thisNode__, PROPS.name$49Oo).getBytes().length + SPropertyOperations.getString(__thisNode__, PROPS.contents$4axr).getBytes().length + nameLength.length);

    return 1 + lenBytes.length + nameLength.length + SPropertyOperations.getString(__thisNode__, PROPS.name$49Oo).getBytes().length + SPropertyOperations.getString(__thisNode__, PROPS.contents$4axr).getBytes().length;
  }
  /*package*/ static byte[] bytes_id60rZZzHEXiv(@NotNull SNode __thisNode__) {
    byte[] bytes = new byte[((int) ByteSized__BehaviorDescriptor.byte_size_id60rZZzHEXgh.invoke(__thisNode__))];

    byte[] nameLength = Bytes.u32BytesLeb128(SPropertyOperations.getString(__thisNode__, PROPS.name$49Oo).getBytes().length);
    byte[] lenBytes = Bytes.u32BytesLeb128(SPropertyOperations.getString(__thisNode__, PROPS.name$49Oo).getBytes().length + SPropertyOperations.getString(__thisNode__, PROPS.contents$4axr).getBytes().length + nameLength.length);

    bytes[0] = ((byte) 0x00);

    int i = 1;
    System.arraycopy(lenBytes, 0, bytes, i, lenBytes.length);
    i += lenBytes.length;

    System.arraycopy(nameLength, 0, bytes, i, nameLength.length);
    i += nameLength.length;

    byte[] nameBytes = SPropertyOperations.getString(__thisNode__, PROPS.name$49Oo).getBytes();
    System.arraycopy(nameBytes, 0, bytes, i, nameBytes.length);
    i += nameBytes.length;

    byte[] contentsBytes = SPropertyOperations.getString(__thisNode__, PROPS.contents$4axr).getBytes();
    System.arraycopy(contentsBytes, 0, bytes, i, contentsBytes.length);

    return bytes;
  }

  /*package*/ CustomSection__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((Integer) byte_size_id60rZZzHEXgh(node));
      case 1:
        return (T) ((byte[]) bytes_id60rZZzHEXiv(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$49Oo = MetaAdapterFactory.getProperty(0xf0ceec7784bd4104L, 0xb53284a17dffbb8aL, 0x601bfff8ed8786cbL, 0x601bfff8ed8786d2L, "name");
    /*package*/ static final SProperty contents$4axr = MetaAdapterFactory.getProperty(0xf0ceec7784bd4104L, 0xb53284a17dffbb8aL, 0x601bfff8ed8786cbL, 0x601bfff8ed8786d5L, "contents");
  }
}
