package WebAssembly.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SectionType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SectionType() {
    super(0xf0ceec7784bd4104L, 0xb53284a17dffbb8aL, 0x601bfff8ed7a492aL, "SectionType", "r:7f03fe05-6980-4670-bfaf-c0d58cc0289a(WebAssembly.structure)/6925410296613456170");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_custom_0 = new EnumerationDescriptor.MemberDescriptor("custom", "custom", 0x601bfff8ed7a492bL, "r:7f03fe05-6980-4670-bfaf-c0d58cc0289a(WebAssembly.structure)/6925410296613456171");
  private final EnumerationDescriptor.MemberDescriptor myMember_type_0 = new EnumerationDescriptor.MemberDescriptor("type", "type", 0x601bfff8ed7a492dL, "r:7f03fe05-6980-4670-bfaf-c0d58cc0289a(WebAssembly.structure)/6925410296613456173");
  private final EnumerationDescriptor.MemberDescriptor myMember_import_0 = new EnumerationDescriptor.MemberDescriptor("import", "import", 0x601bfff8ed7a4931L, "r:7f03fe05-6980-4670-bfaf-c0d58cc0289a(WebAssembly.structure)/6925410296613456177");
  private final EnumerationDescriptor.MemberDescriptor myMember_function_0 = new EnumerationDescriptor.MemberDescriptor("function", "function", 0x601bfff8ed7a4936L, "r:7f03fe05-6980-4670-bfaf-c0d58cc0289a(WebAssembly.structure)/6925410296613456182");
  private final EnumerationDescriptor.MemberDescriptor myMember_table_0 = new EnumerationDescriptor.MemberDescriptor("table", "table", 0x601bfff8ed7a493cL, "r:7f03fe05-6980-4670-bfaf-c0d58cc0289a(WebAssembly.structure)/6925410296613456188");
  private final EnumerationDescriptor.MemberDescriptor myMember_memory_0 = new EnumerationDescriptor.MemberDescriptor("memory", "memory", 0x601bfff8ed7a4943L, "r:7f03fe05-6980-4670-bfaf-c0d58cc0289a(WebAssembly.structure)/6925410296613456195");
  private final EnumerationDescriptor.MemberDescriptor myMember_global_0 = new EnumerationDescriptor.MemberDescriptor("global", "global", 0x601bfff8ed7a494bL, "r:7f03fe05-6980-4670-bfaf-c0d58cc0289a(WebAssembly.structure)/6925410296613456203");
  private final EnumerationDescriptor.MemberDescriptor myMember_export_0 = new EnumerationDescriptor.MemberDescriptor("export", "export", 0x601bfff8ed7a4954L, "r:7f03fe05-6980-4670-bfaf-c0d58cc0289a(WebAssembly.structure)/6925410296613456212");
  private final EnumerationDescriptor.MemberDescriptor myMember_start_0 = new EnumerationDescriptor.MemberDescriptor("start", "start", 0x601bfff8ed7a495eL, "r:7f03fe05-6980-4670-bfaf-c0d58cc0289a(WebAssembly.structure)/6925410296613456222");
  private final EnumerationDescriptor.MemberDescriptor myMember_element_0 = new EnumerationDescriptor.MemberDescriptor("element", "element", 0x601bfff8ed7a4969L, "r:7f03fe05-6980-4670-bfaf-c0d58cc0289a(WebAssembly.structure)/6925410296613456233");
  private final EnumerationDescriptor.MemberDescriptor myMember_code_0 = new EnumerationDescriptor.MemberDescriptor("code", "code", 0x601bfff8ed7a4975L, "r:7f03fe05-6980-4670-bfaf-c0d58cc0289a(WebAssembly.structure)/6925410296613456245");
  private final EnumerationDescriptor.MemberDescriptor myMember_data_0 = new EnumerationDescriptor.MemberDescriptor("data", "data", 0x601bfff8ed7a4982L, "r:7f03fe05-6980-4670-bfaf-c0d58cc0289a(WebAssembly.structure)/6925410296613456258");
  private final EnumerationDescriptor.MemberDescriptor myMember_data_count_0 = new EnumerationDescriptor.MemberDescriptor("data_count", "data_count", 0x601bfff8ed7a4990L, "r:7f03fe05-6980-4670-bfaf-c0d58cc0289a(WebAssembly.structure)/6925410296613456272");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xf0ceec7784bd4104L, 0xb53284a17dffbb8aL, 0x601bfff8ed7a492aL, 0x601bfff8ed7a492bL, 0x601bfff8ed7a492dL, 0x601bfff8ed7a4931L, 0x601bfff8ed7a4936L, 0x601bfff8ed7a493cL, 0x601bfff8ed7a4943L, 0x601bfff8ed7a494bL, 0x601bfff8ed7a4954L, 0x601bfff8ed7a495eL, 0x601bfff8ed7a4969L, 0x601bfff8ed7a4975L, 0x601bfff8ed7a4982L, 0x601bfff8ed7a4990L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_custom_0, myMember_type_0, myMember_import_0, myMember_function_0, myMember_table_0, myMember_memory_0, myMember_global_0, myMember_export_0, myMember_start_0, myMember_element_0, myMember_code_0, myMember_data_0, myMember_data_count_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "custom":
        return myMember_custom_0;
      case "type":
        return myMember_type_0;
      case "import":
        return myMember_import_0;
      case "function":
        return myMember_function_0;
      case "table":
        return myMember_table_0;
      case "memory":
        return myMember_memory_0;
      case "global":
        return myMember_global_0;
      case "export":
        return myMember_export_0;
      case "start":
        return myMember_start_0;
      case "element":
        return myMember_element_0;
      case "code":
        return myMember_code_0;
      case "data":
        return myMember_data_0;
      case "data_count":
        return myMember_data_count_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
