package WebAssembly.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.style.AbstractStyleClass;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.editor.runtime.descriptor.EditorBuilderEnvironment;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.nodeEditor.MPSColors;

public class main_StyleSheet {
  public static class sectionnameStyleClass extends AbstractStyleClass {
    public sectionnameStyleClass(EditorContext editorContext, SNode node) {
      super(editorContext, node);
    }
    public sectionnameStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
      style.set(StyleAttributes.TEXT_COLOR, getStyleRegistry().getSimpleColor(MPSColors.yellow));
    }

  }
  public static class section_itemnameStyleClass extends AbstractStyleClass {
    public section_itemnameStyleClass(EditorContext editorContext, SNode node) {
      super(editorContext, node);
    }
    public section_itemnameStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
      style.set(StyleAttributes.TEXT_COLOR, getStyleRegistry().getSimpleColor(MPSColors.pink));
    }

  }
  public static class valtypeStyleClass extends AbstractStyleClass {
    public valtypeStyleClass(EditorContext editorContext, SNode node) {
      super(editorContext, node);
    }
    public valtypeStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
      style.set(StyleAttributes.TEXT_COLOR, getStyleRegistry().getSimpleColor(MPSColors.DARK_MAGENTA));
    }

  }
  public static class numericStyleClass extends AbstractStyleClass {
    public numericStyleClass(EditorContext editorContext, SNode node) {
      super(editorContext, node);
    }
    public numericStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
      style.set(StyleAttributes.TEXT_COLOR, getStyleRegistry().getSimpleColor(MPSColors.red));
    }

  }
  public static class stringStyleClass extends AbstractStyleClass {
    public stringStyleClass(EditorContext editorContext, SNode node) {
      super(editorContext, node);
    }
    public stringStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
      style.set(StyleAttributes.TEXT_COLOR, getStyleRegistry().getSimpleColor(MPSColors.cyan));
    }

  }
  public static class instrStyleClass extends AbstractStyleClass {
    public instrStyleClass(EditorContext editorContext, SNode node) {
      super(editorContext, node);
    }
    public instrStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
    }

  }
  public static class blockstartStyleClass extends AbstractStyleClass {
    public blockstartStyleClass(EditorContext editorContext, SNode node) {
      super(editorContext, node);
    }
    public blockstartStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
      style.set(StyleAttributes.TEXT_COLOR, getStyleRegistry().getSimpleColor(MPSColors.pink));
    }

  }
  public static class blockendStyleClass extends AbstractStyleClass {
    public blockendStyleClass(EditorContext editorContext, SNode node) {
      super(editorContext, node);
    }
    public blockendStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
      style.set(StyleAttributes.TEXT_COLOR, getStyleRegistry().getSimpleColor(MPSColors.magenta));
    }

  }
}
