package WebassemblyText.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.typesystem.inference.EquationInfo;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class typeof_LocalGet_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_LocalGet_InferenceRule() {
  }
  public void applyRule(final SNode localGet, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    StackState state = StackState.atInstr(localGet);
    StackItem stackItem = state.itemAtIndex(SLinkOperations.getTarget(localGet, LINKS.x$ziAZ));

    if (stackItem != null) {
      {
        SNode _nodeToCheck_1029348928467 = localGet;
        EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:53b811bf-ce98-4eeb-819f-783007083750(WebassemblyText.typesystem)", "6925410296604660207", 0, null);
        typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:53b811bf-ce98-4eeb-819f-783007083750(WebassemblyText.typesystem)", "6925410296604658870", true), (SNode) stackItem.itemType, _info_12389875345);
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.LocalGet$Xp;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink x$ziAZ = MetaAdapterFactory.getContainmentLink(0x3ffc45fa71954470L, 0x834ba6b1a95f90d6L, 0x601bfff8ec57bf17L, 0x601bfff8ec57f878L, "x");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept LocalGet$Xp = MetaAdapterFactory.getConcept(0x3ffc45fa71954470L, 0x834ba6b1a95f90d6L, 0x601bfff8ec57bf17L, "WebassemblyText.structure.LocalGet");
  }
}
