package WebassemblyText.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class I32BinOp_Constraints extends BaseConstraintsDescriptor {
  public I32BinOp_Constraints() {
    super(CONCEPTS.I32BinOp$Fx);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept I32BinOp$Fx = MetaAdapterFactory.getConcept(0x3ffc45fa71954470L, 0x834ba6b1a95f90d6L, 0x601bfff8ec4a11e1L, "WebassemblyText.structure.I32BinOp");
  }
}
